### PR TITLE
Feature playing

### PR DESCRIPTION
**Pull request by grburgess**
added some more plotting stuffs

### CODE REVIEW

**Comment by Migelo** [comment]
Binder complains:

```
ResolvePackageNotFound:
- numpy-html
```

**Comment by grburgess** [comment]
Is it py3?

**Comment by Migelo** [comment]
The docker image I request is python 3.6

**Comment by grburgess** [comment]
strange. I would just cut it out then

**Comment by Migelo** [comment]
Will you fix it or should I merge it and fix?

**Comment by grburgess** [comment]
I did it

**Pull request merged**
